#pragma once

#define KEY_FEEDBACK_POMODORO 0
#define KEY_FEEDBACK_POMODORO_CYCLE 1
#define PERSIST_KEY_ID_POMODORO 1
#define PERSIST_KEY_ID_POMODORO_CYCLE 2
#define PERSIST_KEY_ID_POMODORO_CYCLE_NOW 3
